# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False, verbose_name='Пропуск')),
                ('grade', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('timeserver', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'Журнал',
                'ordering': ['timeserver'],
            },
        ),
        migrations.CreateModel(
            name='Specalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'студента',
                'verbose_name_plural': 'Студенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('time', models.PositiveIntegerField(verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'преподавателя',
                'verbose_name_plural': 'Преподователи',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='journal',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='group',
            name='specalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Specalty', verbose_name='Специальность'),
        ),
    ]
